### ISSUE TITLE
Sequential execution of scripts separated by '&&' 

### ISSUE THREAD

**Issue by cybertronbaka** [cybertronbaka/loki#16]
Currently unable to run scripts with exec which contains 2 or more commands separated by `&&`:

```yaml
...
scripts:
  test:
    exec: cd ../packages && dart pub get
```
