### ISSUE TITLE
Recursive Scripts

### ISSUE THREAD

**Issue by cybertronbaka** [cybertronbaka/loki#17]
Right now when calling `loki run <script command>` from another script. It runs the entire process of 
- loading loki.yaml
- reading projects
- reading devices (if `loki app <appname>`)

Sample yaml:
```yaml
...
scripts:
  get:
    exec: dart pub get
  analyze:
    exec: dart pub analyze
  get:analyze:
    exec: loki run exec && loki run analyze
```

Solution:
Get rid of  verbose info on later loki runs. instead of calling a process directly call loki base.
